def container

pipeline {

  agent any

  options {
    timeout(time: 1, unit: 'HOURS')
    timestamps()
  }

  stages {
    /* Checkout git repo with Dockerfiles to build and create a shortened commit ID
     * that will be used in tagging containers pushed to Docker Hub */
    stage('Clone repository') {
      steps {
        checkout scm
        script {
          shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
        }
      }
    }

    // Build container
    stage('Build image') {
      steps {
        script {
          container = docker.build("pawsey/hpc-python", "./hpc-python")
        }
      }
    }

    // Test Docker build
    stage('Test NumPy') {
      steps {
        script {
          sh 'echo "Running tests"'
          container.inside("--name='numpy-test'") {
            sh 'python -c "import numpy; numpy.test();"'
          }
        }
      }
    }

    /* Push image to public Docker Hub with 2 tags:
     *  - Jenkins build tag
     *  - latest tag */
    stage('Push image') {
      steps {
        script {
          docker.withRegistry('', 'dockerhub-credentials-bskjerven') {
            container.push("jenkins-build-${shortCommit}-${env.BUILD_TIMESTAMP}")
            container.push("latest")
          }
        }
      }
    }
  }

  post {
    always {
      script {
        sh 'docker rmi pawsey/hpc-python'
      }
    }
    failure {
      emailext (
        subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
          <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        recipientProviders: [[$class: 'RequesterRecipientProvider']]
      )
    }
    changed 
      emailext (
        subject: "CHANGED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: '''${SCRIPT, template="groovy-html.template"}''',
        recipientProviders: [[$class: 'RequesterRecipientProvider']]
      )
    }
    success {
      emailext (
        subject: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: '''${SCRIPT, template="groovy-html.template"}''',
        recipientProviders: [[$class: 'RequesterRecipientProvider']]
      )
    }
  }
}
