def container

pipeline {

  agent any

  options {
    timeout(time: 1, unit: 'HOURS')
    timestamps()
  }

  stages {
    /* Checkout git repo with Dockerfiles to build and create a shortened commit ID
     * that will be used in tagging containers pushed to Docker Hub */
    stage('Clone repository') {
      steps {
        checkout scm
        script {
          shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
        }
      }
    }

    // Build container
    stage('Build image') {
      steps {
        script {
          container = docker.build("pawsey/hpc-python")
        }
      }
    }

    // Test Docker build
    stage('Test NumPy') {
      steps {
        script {
          sh 'echo "Running tests"'
          container.inside("--name='numpy-test'") {
            s<%  %> 'python -c "import numpy; numpy.test("full");"'
          }
        }
      }
    }

    /* Push image to public Docker Hub with 2 tags:
     *  - Jenkins build tag
     *  - latest tag */
    stage('Push image') {
      steps {
        script {
          docker.withRegistry('', 'docker-hub-credentials') {
            container.push("jenkins-build-${shortCommit}-${env.BUILD_TIMESTAMP}")
            container.push("latest")
          }
        }
      }
    }
  }

  post {
    always {
      script {
        sh 'echo "docker rmi bskjerven/mwa-docker"'
      }
    }
    failure {
      emailext (
        subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
          <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        recipientProviders: [[$class: 'DevelopersRecipientProvider']]
      )
    }
    changed {
      emailext (
        subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
          <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        recipientProviders: [[$class: 'DevelopersRecipientProvider']]
      )
    }
  }
}
